# Generated by Django 5.1.7 on 2025-04-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_url', models.URLField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('repos_count', models.PositiveIntegerField(default=0)),
                ('languages', models.TextField(blank=True, null=True)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('matched_skills', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Individual', 'Individual'), ('Job-seeker', 'Job-seeker')], default='Individual', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(max_length=500),
        ),
    ]
