# Generated by Django 5.1.7 on 2025-04-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0005_quizquestion_for_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Individual', 'Individual'), ('Job-seeker', 'Job-seeker')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(),
        ),
    ]
